# Generated by Django 4.0.4 on 2022-06-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated',)},
        ),
    ]
